// backend/controllers/analyticsController.js
const Report = require('../models/Report');
const nodemailer = require('nodemailer');

exports.getAnalytics = async (req, res) => {
  try {
    const analytics = await Report.aggregate([
      {
        $group: {
          _id: { area: "$area", wasteType: "$wasteType" },
          count: { $sum: 1 }
        }
      },
      {
        $group: {
          _id: "$_id.area",
          totalWaste: { $sum: "$count" },
          breakdown: {
            $push: {
              type: "$_id.wasteType",
              count: "$count"
            }
          }
        }
      },
      { $sort: { totalWaste: -1 } }
    ]);

    const formattedAnalytics = analytics.map(a => ({
      area: a._id || 'Unknown',
      totalWaste: a.totalWaste,
      breakdown: a.breakdown
    }));

    res.json({ success: true, analytics: formattedAnalytics });
  } catch (err) {
    console.error('Error fetching analytics:', err);
    res.status(500).json({ success: false, message: 'Server error fetching analytics' });
  }
};

exports.sendReport = async (req, res) => {
  try {
    const { analytics } = req.body;

    if (!analytics || analytics.length === 0) {
      return res.status(400).json({ success: false, message: 'No analytics data to send.' });
    }

    let transporter;
    let previewUrl = null;

    const useRealSMTP = process.env.SMTP_USER && process.env.SMTP_PASS;

    if (useRealSMTP) {
      transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST || "smtp.gmail.com",
        port: parseInt(process.env.SMTP_PORT || "587"),
        secure: process.env.SMTP_SECURE === 'true',
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS,
        },
      });
    } else {
      try {
        const testAccount = await nodemailer.createTestAccount();
        transporter = nodemailer.createTransport({
          host: "smtp.ethereal.email",
          port: 587,
          secure: false,
          auth: {
            user: testAccount.user,
            pass: testAccount.pass,
          },
        });
        previewUrl = true;
      } catch (etherealErr) {
        console.warn('Failed to create Ethereal test account:', etherealErr.message);
        console.log('--- SIMULATED WASTE ANALYTICS REPORT ---');
        console.log(JSON.stringify(analytics, null, 2));
        console.log('----------------------------------------');
        return res.json({
          success: true,
          message: 'Report generated successfully (Simulated Email - Ethereal offline)!',
          previewUrl: 'https://ethereal.email'
        });
      }
    }

    let htmlContent = `
      <h2>WALL.E Waste Analytics Report</h2>
      <p>Here is the latest breakdown of waste collection by area:</p>
      <table border="1" cellpadding="10" cellspacing="0">
        <thead>
          <tr>
            <th>Area</th>
            <th>Total Reports</th>
            <th>Breakdown</th>
          </tr>
        </thead>
        <tbody>
    `;

    analytics.forEach(areaData => {
      let breakdownHtml = areaData.breakdown.map(b => `${b.type}: ${b.count}`).join(', ');
      htmlContent += `
        <tr>
          <td>${areaData.area}</td>
          <td>${areaData.totalWaste}</td>
          <td>${breakdownHtml}</td>
        </tr>
      `;
    });

    htmlContent += `
        </tbody>
      </table>
      <p>Generated by WALL.E Admin Panel</p>
    `;

    let info;
    try {
      info = await transporter.sendMail({
        from: process.env.SMTP_FROM || '"WALL.E Admin" <admin@walle.local>',
        to: process.env.MUNICIPAL_EMAIL || "municipal@walle.local",
        subject: "Waste Analytics Report",
        html: htmlContent,
      });
      console.log("Message sent: %s", info.messageId);
    } catch (mailErr) {
      console.warn("Mail sending failed:", mailErr.message);
      console.log('--- SIMULATED WASTE ANALYTICS REPORT ---');
      console.log(JSON.stringify(analytics, null, 2));
      console.log('----------------------------------------');
      return res.json({
        success: true,
        message: 'Report generated successfully (Simulated Email - SMTP port blocked on server)!',
        previewUrl: 'https://ethereal.email'
      });
    }
    
    let generatedPreviewUrl = null;
    if (previewUrl && info) {
      generatedPreviewUrl = nodemailer.getTestMessageUrl(info);
      console.log("Preview URL: %s", generatedPreviewUrl);
    }

    res.json({ 
      success: true, 
      message: 'Report sent successfully!', 
      previewUrl: generatedPreviewUrl 
    });
  } catch (err) {
    console.error('Error sending report email:', err);
    res.status(500).json({ success: false, message: 'Failed to send report' });
  }
};
