// backend/controllers/analyticsController.js
const Report = require('../models/Report');
const nodemailer = require('nodemailer');

exports.getAnalytics = async (req, res) => {
  try {
    const analytics = await Report.aggregate([
      {
        $group: {
          _id: { area: "$area", wasteType: "$wasteType" },
          count: { $sum: 1 }
        }
      },
      {
        $group: {
          _id: "$_id.area",
          totalWaste: { $sum: "$count" },
          breakdown: {
            $push: {
              type: "$_id.wasteType",
              count: "$count"
            }
          }
        }
      },
      { $sort: { totalWaste: -1 } }
    ]);

    const formattedAnalytics = analytics.map(a => ({
      area: a._id || 'Unknown',
      totalWaste: a.totalWaste,
      breakdown: a.breakdown
    }));

    res.json({ success: true, analytics: formattedAnalytics });
  } catch (err) {
    console.error('Error fetching analytics:', err);
    res.status(500).json({ success: false, message: 'Server error fetching analytics' });
  }
};

exports.sendReport = async (req, res) => {
  try {
    const { analytics } = req.body;

    if (!analytics || analytics.length === 0) {
      return res.status(400).json({ success: false, message: 'No analytics data to send.' });
    }

    // Use Ethereal for testing, or use real SMTP if provided in .env
    const testAccount = await nodemailer.createTestAccount();
    
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smtp.ethereal.email",
      port: process.env.SMTP_PORT || 587,
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER || testAccount.user,
        pass: process.env.SMTP_PASS || testAccount.pass,
      },
    });

    let htmlContent = `
      <h2>WALL.E Waste Analytics Report</h2>
      <p>Here is the latest breakdown of waste collection by area:</p>
      <table border="1" cellpadding="10" cellspacing="0">
        <thead>
          <tr>
            <th>Area</th>
            <th>Total Reports</th>
            <th>Breakdown</th>
          </tr>
        </thead>
        <tbody>
    `;

    analytics.forEach(areaData => {
      let breakdownHtml = areaData.breakdown.map(b => `${b.type}: ${b.count}`).join(', ');
      htmlContent += `
        <tr>
          <td>${areaData.area}</td>
          <td>${areaData.totalWaste}</td>
          <td>${breakdownHtml}</td>
        </tr>
      `;
    });

    htmlContent += `
        </tbody>
      </table>
      <p>Generated by WALL.E Admin Panel</p>
    `;

    let info = await transporter.sendMail({
      from: '"WALL.E Admin" <admin@walle.local>',
      to: process.env.MUNICIPAL_EMAIL || "municipal@walle.local",
      subject: "Waste Analytics Report",
      html: htmlContent,
    });

    console.log("Message sent: %s", info.messageId);
    console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));

    res.json({ 
      success: true, 
      message: 'Report sent successfully!', 
      previewUrl: nodemailer.getTestMessageUrl(info) 
    });
  } catch (err) {
    console.error('Error sending report email:', err);
    res.status(500).json({ success: false, message: 'Failed to send report' });
  }
};
